# Generated by Django 5.2.12 on 2026-04-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_reviewer', '0002_codesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='json_review',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++')], max_length=50),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='result',
            field=models.TextField(blank=True),
        ),
    ]
